<<<<<<< HEAD
# Generated by Django 3.2.9 on 2022-01-11 02:56
=======
# Generated by Django 3.2.9 on 2022-02-03 17:17
>>>>>>> 87805e91c0fca8bbcf80160d4ff6ebc9c6343f54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Carts', '0001_initial'),
=======
        ('Carts', '0001_initial'),
        ('Products', '0001_initial'),
>>>>>>> 87805e91c0fca8bbcf80160d4ff6ebc9c6343f54
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carts.cart'),
        ),
    ]
