# Generated by Django 3.2.9 on 2022-01-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0003_auto_20211221_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
