# Generated by Django 3.2.9 on 2021-12-27 01:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0002_auto_20211224_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['comment', 'myuser'], 'verbose_name': 'Comment Voting', 'verbose_name_plural': 'Comment Votings'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('up_or_down', 'myuser')},
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_flagged', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.comment')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Flag',
                'verbose_name_plural': 'Comment Flags',
                'ordering': ['comment', 'myuser'],
                'unique_together': {('is_flagged', 'myuser')},
            },
        ),
    ]
