# Generated by Django 3.2.9 on 2021-12-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20211227_0200'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together=set(),
        ),
    ]
