# Generated by Django 3.2.9 on 2021-12-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_flag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_flagged',
            field=models.BooleanField(default=True),
        ),
    ]
