# Generated by Django 3.2.9 on 2021-12-06 13:22

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='picture',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
