# Generated by Django 3.2.9 on 2021-12-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20211206_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['product'], 'verbose_name': 'Product Picture', 'verbose_name_plural': 'Product Pictures'},
        ),
        migrations.AlterUniqueTogether(
            name='picture',
            unique_together={('product',)},
        ),
        migrations.RemoveField(
            model_name='picture',
            name='order',
        ),
    ]
