# Generated by Django 3.2.9 on 2021-12-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_comment_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
