# Generated by Django 3.2.9 on 2021-12-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pictures',
            field=models.FileField(blank=True, null=True, upload_to='product_pictures/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
