# Generated by Django 3.2.9 on 2021-12-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20211206_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
    ]
