# Generated by Django 3.2.9 on 2021-12-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_picture_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pictures',
            field=models.FileField(upload_to='product_pictures/'),
        ),
    ]
