# Generated by Django 3.2.9 on 2021-12-12 21:56

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_picture_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='helpful',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='not_helpful',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_helpful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pictures',
            field=models.FileField(upload_to=Products.models.get_image_filename),
        ),
    ]
