# Generated by Django 3.2.9 on 2021-12-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_auto_20211213_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
