# Generated by Django 3.2.9 on 2021-12-21 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0014_comment_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.comment')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Rating',
                'verbose_name_plural': 'Comment Ratings',
                'ordering': ['comment', 'myuser'],
                'unique_together': {('comment', 'myuser')},
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
