# Generated by Django 3.2.9 on 2021-12-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_auto_20211221_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={},
        ),
        migrations.AddField(
            model_name='vote',
            name='up_or_down',
            field=models.CharField(choices=[('U', 'up'), ('D', 'down')], default=0, max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
