# Generated by Django 3.2.9 on 2022-01-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_comment_title'),
        ('Products', '0005_auto_20211221_1413'),
        ('Products', '0016_auto_20211221_1511'),
    ]

    operations = [
    ]
