# Generated by Django 3.2.9 on 2022-01-04 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_merge_0005_auto_20211221_1413_0016_auto_20211221_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='helpful',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_helpful',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='not_helpful',
        ),
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
