# Generated by Django 3.2.9 on 2022-01-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_merge_20220102_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='helpful',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_helpful',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='not_helpful',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
